
# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  # Uncomment this if you want to bring up
  # the  machines with a GUI
  #config.vm.provider "virtualbox" do |v|
  #  v.gui = true
  #end


  config.vm.define "controller" do |controller|
    controller.vm.hostname = "controller"
    controller.vm.box = "generic/ubuntu1804"
    controller.vm.network "private_network", ip: "192.168.56.11", name: 'Host-Only #1'
    # This configuration assumes that we have already created two hostonly networks called Host-Only #1 and Host-Only #2
    # If this has not been done, please run the script ../scripts/createVBoxNetworks.sh
    # as auto_config is set to false, VirtualBox should not actually assign IP addresses
    controller.vm.network "private_network", ip: "172.16.0.12",  auto_config: false, name: 'Host-Only #2'
    controller.vm.network "forwarded_port", guest: 22, host: 8222
    controller.vm.provider "parallels" do |v|
      ##v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      ##v.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      v.memory = 6144
      v.cpus = 2
    end
  end

  config.vm.define "compute1" do |compute1|
    compute1.vm.hostname = "compute1"
    compute1.vm.box = "generic/ubuntu1804"
    compute1.vm.network "private_network", ip: "192.168.56.21", name: 'Host-Only #1'
    compute1.vm.network "private_network", ip: "172.16.0.13",  auto_config: false, name: 'Host-Only #2'
    compute1.vm.network "forwarded_port", guest: 22, host: 8200
    compute1.vm.provider "parallels" do |v|
      ##v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      ##v.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      v.memory = 4096
      v.cpus = 2
    end
  end

  config.vm.define "compute2" do |compute2|
    compute2.vm.hostname = "compute2"
    compute2.vm.box = "generic/ubuntu1804"
    compute2.vm.network "private_network", ip: "192.168.56.22", name: 'Host-Only #1'
    compute2.vm.network "private_network", ip: "172.16.0.14",  auto_config: false, name: 'Host-Only #2'
    compute2.vm.network "forwarded_port", guest: 22, host: 8201
    compute2.vm.provider "parallels" do |v|
      ##v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      ##v.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
      v.memory = 4096
      v.cpus = 2
    end
  end


end
